# Generated by Django 4.2.2 on 2023-07-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='username',
            new_name='user',
        ),
    ]
