# Generated by Django 4.2.2 on 2023-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
