# Generated by Django 4.2.2 on 2023-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_comment_rating_alter_supply_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplies/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
