# Generated by Django 4.2.2 on 2023-08-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_supply_image_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='picture',
        ),
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
