# Generated by Django 4.2.2 on 2023-08-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_remove_supply_picture_alter_supply_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
